### ISSUE TITLE
release_id的疑问

### ISSUE THREAD

**Issue by djjowfy** [hugeterry/UpdateDemo#1]
fir.im每次应用上传新版本后的release_id都不一样，那么这个应该是写哪次的release_id呢？

**Comment by hugeterry** [comment]
同个应用上传新版本release_id是固定不变的😋

**Comment by djjowfy** [comment]
不啊。比如
[http://fir.im/AirQualityMeasure?release_id=579a1732548b7a3a9000117a](url)
[http://fir.im/AirQualityMeasure?release_id=579cc511959d6937b00017e6](url)
这是我的一个应用。但根据链接可以得到release_id变了

**Comment by hugeterry** [comment]
http://api.fir.im/apps/latest/xxx?api_token=xxx #使用 `id` 获取更新，获取的json提取installUrl字段是当前应用的最新版本
而且我刚刚在试了一下，自己上传的同个应用不同版本上传后release_id是固定不变的哦

**Comment by djjowfy** [comment]
[url](http://fir.im/docs)。fir.im的官方api文档里面有release_id Release 表示一个版本的唯一 id。然后你所给的链接里面的id并不是release_id。而是应用id,根据文档：id 应用id，可在"应用管理"->"基本信息"查看

**Comment by hugeterry** [comment]
是我的疏忽😋
谢谢你
