### ISSUE TITLE
stack=java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/TintManager;

### ISSUE THREAD

**Issue by s162738** [hugeterry/UpdateDemo#10]
stack=java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/TintManager;

应该是包 出冲突了。添加    compile 'cn.hugeterry.updatefun:updatefun:1.6.8'  后会报这个错误。

我用的是
  compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'

**Comment by hugeterry** [comment]
hello,我用的是23.3.0的版本，是包冲突
你先使用23.3.0吧，稍后我看一下具体是什么类导致的，修改一下
谢谢你的反馈😋

**Comment by s162738** [comment]
好的。多谢。

**Comment by s162738** [comment]
我换了23.3.0.现在没问题了。还有2个问题，
1、打开app后会验证是否需要更新，  那我后面，在设置中选择手动更新时候，怎么再次弹出更新面板？
2、有没办法，让更新界面选择操作后 再执行后面的代码。 目前的更新是异步的，不影响主程序。最好updateFunGO() 方法能返回一个值。选择取消后，返回false, 就可以判断是否继续执行后面的代码。

**Comment by hugeterry** [comment]
已在新版本1.8.4中添加手动更新功能，请重新依赖😋

###手动更新（需1.8.4以上版本）

请确保在你的app已添加依赖(见用法Step 1),
并已经写上你fir.im账号的API_TOKEN以及APP的应用ID(见用法Step 2)

在需要手动更新时调用:

```
UpdateFunGO. manualStart(this);
```

并在手动更新的当前Activity添加上以下代码：

```
 @Override
    protected void onResume() {
        super.onResume();
        UpdateFunGO.onResume(this);
    }
  @Override
     protected void onStop() {
         super.onStop();
         UpdateFunGO.onStop(this);
     }
```

即可实现手动更新
