### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by melodicdeath** [hugeterry/UpdateDemo#11]
Android4.4.2报错：
java.io.FileNotFoundException: /sdcard/UpdateFun/xxxxx.apk: open failed: EACCES (Permission denied)
加权限也没用

**Comment by hugeterry** [comment]
方便把你手机型号提供给我吗？

**Comment by hugeterry** [comment]
已经发布新版本，请重新依赖compile 'cn.hugeterry.updatefun:updatefun:1.7.0'
然后试试看还有没有报错，向我反馈一下😋

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000

## 08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk

08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

```
}
```

---

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by melodicdeath** [comment]
华为荣耀6，没有root
1.7.0我试了还是这个错
我下了您的源码把下载位置改到了/data/data/packagename下，可以下载了，最后安装的时候提示解析包时出现问题

08-27 11:54:30.425 4445-4575/org.melodicdeath.hncmatcedu I/UpdateFun TAG: ApkDownloadUrl:http://download.fir.im/v2/app/install/57bdcf6b959d696d9800000d?download_token=1494eb6d3745bb85fac43d53c2357de3
08-27 11:54:30.475 4445-4445/org.melodicdeath.hncmatcedu D/mali_winsys: new_window_surface returns 0x3000
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu I/UpdateFun TAG: apk检验:包名相同,安装apk
--------
08-27 11:54:34.725 4445-4445/org.melodicdeath.hncmatcedu D/test2: /data/data/org.melodicdeath.hncmatcedu/org.melodicdeath.hncmatcedu.apk
这是我自己从startInstall方法中打印的filepath，文件好像是存在的

public static void startInstall(Context context, String filePath) {
        File apkfile = new File(filePath);
        if (!apkfile.exists()) {
            Log.e("test",filePath);
            return;
        }
        Log.d("test2",filePath);
        Intent i = new Intent(Intent.ACTION_VIEW);
        i.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                "application/vnd.android.package-archive");
        context.startActivity(i);

    }
------

**Comment by hugeterry** [comment]
更新路径下的apk是否是已签名的？如果已签名的下载包覆盖安装了直接通过as调试用的未签名的apk，是会报解析包错误的提示的

**Comment by melodicdeath** [comment]
是的。
但是我打包了一个签名的release版安装以后更新还是报解析失败，这是为什么？
Android这块不是特别熟。

**Comment by melodicdeath** [comment]
下次找个root的手机试试

**Comment by hugeterry** [comment]
跟root似乎没有关系，因为到现在其他手机还是没问题的，你是第一例发生解析失败的情况，
包名，签名钥匙要相同，更新的版本需比当前版本高，这样下应该是不会出现解析失败的情况

**Comment by melodicdeath** [comment]
用root过的手机下载到/sdcard/UpdateFun中可以更新

**Comment by melodicdeath** [comment]
解析失败可能是因为/data/data/packagename下没有执行权限
我试了其他几款手机，包括root和未root的，都可以写入sdcard并且可以更新成功
所以可能是荣耀6的问题

**Comment by hugeterry** [comment]
好的，我近期会修复一下，您看看有没有能在荣耀6下保存文件能取得权限的方法

**Comment by melodicdeath** [comment]
好的，如果找到我会发上来

**Comment by melodicdeath** [comment]
还有一个问题，我觉得有必要加一个强制更新的功能，鉴于fir.im没有相关标志，就通过读取固定版本号来判断是否强制更新（比如最后是.0的版本）
如果您也觉得有必要的话我到时候fork下来给你发pull request

**Comment by hugeterry** [comment]
1.8.4版本修改了路径，用开源的工具类找到路径去读写，理论上能适配更多手机
您再试试看荣耀有没有问题
