### ISSUE TITLE
android 6.0 解析软件包时出现错误

### ISSUE THREAD

**Issue by osickleo** [hugeterry/UpdateDemo#15]
两个手机 一个android 5.0.1 一个6.0        5.0.1更新后能安装 6.0提示解析软件包时出现错误

**Comment by hugeterry** [comment]
刚拿到6.0的手机，所以回复晚了
测试是没有问题的
请确定使用的apk和下载后的apk都是已签名的

**Comment by quanyousheng** [comment]
Android6.0手机安装了已签名的APK，每次还是提示解析软件包错误，而6.0以下的手机就没这个问题。
