### ISSUE TITLE
为什么dialog里的button是蓝色的？有办法自定义吗？

### ISSUE THREAD

**Issue by JiangShuLiang** [hugeterry/UpdateDemo#18]
如图：
感谢了先！
![_20170206115751](https://cloud.githubusercontent.com/assets/20485764/22634330/a106e5c6-ec63-11e6-9a41-b44951ebbc55.png)

**Comment by hugeterry** [comment]
应该是你的项目文件里或者导入的其他库里已经有drawable/button.xml导致了
更新了新的版本，你可以重新依赖即可以解决该问题
```
dependencies {
    compile 'cn.hugeterry.updatefun:updatefun:1.9.0'
}
```
谢谢你的反馈

**Comment by JiangShuLiang** [comment]
解决了！感谢！！！！！！！
