### ISSUE TITLE
下载地址问题

### ISSUE THREAD

**Issue by shichunlei** [hugeterry/UpdateDemo#2]
![image](https://cloud.githubusercontent.com/assets/7146745/17389322/bd8c3630-5a35-11e6-9791-b13b12512150.png)

"installUrl": "http://download.fir.im/v2/app/install/579eacb4ca87a810a40020e7?download_token=c0cb62b4ca9153d3cd44cafe3ceb3c10"

**Comment by hugeterry** [comment]
是编码问题，在我的浏览器点击链接后下载下来apk的名字也是乱码的，以及报错的原因是在fir.im取得下载链接后为乱码，在android studio里边你开发使用的编码是不是utf-8？能不能给你的apk展示页面我看看呢

**Comment by hugeterry** [comment]
你好，已经修复该bug啦，可以添加新版本的依赖：注意库名也修改了，所以不要只修改版本号最好整条复制添加依赖
在gradle文件中加入下面的依赖:

dependencies {
    compile 'cn.hugeterry.updatefun:updatefun:1.5.0'
}
如果你使用Maven，那么加入下面的依赖：

<dependency>
  <groupId>cn.hugeterry.updatefun</groupId>
  <artifactId>updatefun</artifactId>
  <version>1.5.0</version>
  <type>pom</type>
</dependency>

谢谢你向我提问题 😋

**Comment by hugeterry** [comment]
你好，已经修复该bug啦，可以添加新版本的依赖：注意库名也修改了，不要只修改版本号最好整条复制添加依赖
在gradle文件中加入下面的依赖:

```
dependencies {
    compile 'cn.hugeterry.updatefun:updatefun:1.5.0'
}
```

如果你使用Maven，那么加入下面的依赖：

```
<dependency>
  <groupId>cn.hugeterry.updatefun</groupId>
  <artifactId>updatefun</artifactId>
  <version>1.5.0</version>
  <type>pom</type>
</dependency>
```

谢谢你向我反馈问题😋

**Comment by shichunlei** [comment]
我使用的eclipse    怎么修改？

**Comment by hugeterry** [comment]
那重新下载updatefun文件夹导入到工程里边吧
