### ISSUE TITLE
安卓7.0 安装会直接崩溃

### ISSUE THREAD

**Issue by aesion** [hugeterry/UpdateDemo#23]
http://www.cnblogs.com/yongdaimi/p/6067319.html

安卓7.0 多了安卓权限的问题，这是个大BUG

**Comment by aesion** [comment]
解决办法：
        //http://www.cnblogs.com/yongdaimi/p/6067319.html
        //android-解决 Android N 上 报错：android.os.FileUriExposedException
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(context, "cn.hugeterry.updatedemo.fileprovider", apkfile);
            intent.setDataAndType(contentUri, "application/vnd.android.package-archive");
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            intent.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                    "application/vnd.android.package-archive");
        }

**Comment by aesion** [comment]
解决办法：
`        //http://www.cnblogs.com/yongdaimi/p/6067319.html
        //android-解决 Android N 上 报错：android.os.FileUriExposedException
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(context, "cn.hugeterry.updatedemo.fileprovider", apkfile);
            intent.setDataAndType(contentUri, "application/vnd.android.package-archive");
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            intent.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                    "application/vnd.android.package-archive");
        }


`

**Comment by aesion** [comment]
解决办法：

      //http://www.cnblogs.com/yongdaimi/p/6067319.html
        //android-解决 Android N 上 报错：android.os.FileUriExposedException
`  
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            Uri contentUri = FileProvider.getUriForFile(context, "cn.hugeterry.updatedemo.fileprovider", apkfile);
            intent.setDataAndType(contentUri, "application/vnd.android.package-archive");
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            intent.setDataAndType(Uri.parse("file://" + apkfile.toString()),
                    "application/vnd.android.package-archive");
        }


`

**Comment by JamieYee** [comment]
是要在他的库里面修改吧？@aesion

**Comment by aesion** [comment]
是的，下载源码之后改一改就可以了，作者感觉不打算更新了

**Comment by hugeterry** [comment]
@aesion @yishangfei 很抱歉，这段工作时间一直很忙，没来得及维护，已修改，上传新版本2.0.4，支持7.0
很感谢你们的反馈和建议

**Comment by JamieYee** [comment]
![image](https://cloud.githubusercontent.com/assets/15099278/26230182/8ea9f984-3c79-11e7-970b-ac4460f33a8b.png) @aesion  @hugeterry  这两个冲突有什么解决的办法吗

**Comment by hugeterry** [comment]
@yishangfei hello
你应该也是在你的AndroidManifest里声明了FileProvider，才会遇到该情况
请把你的`<provider>`里面的 android:authorities做修改，改成如下：
 android:authorities="<你的应用包名>.updatefunfileprovider"
