### ISSUE TITLE
更新逻辑

### ISSUE THREAD

**Issue by waincent** [hugeterry/UpdateDemo#8]
看了代码
else if (!DownloadKey.version.equals(version)) {
            Log.i("UpdateFun TAG", "需更新版本");
            msg.arg1 = 1;
            up_handler.sendMessage(msg);

直接判断veriosn不同，导致我现在调试版本升高后，每次调试都要提示升级

**Comment by hugeterry** [comment]
对的，通过判断version不同，如果判断大小可能会出现差错，比如1.1.2跟1.1数字位不同
所以当初在写的时候再上考虑还有比较其他更新方式大部分采取判断不同所以选择判断不同了

**Comment by waincent** [comment]
比较versionCode大小呢？

**Comment by hugeterry** [comment]
这个之前也考虑过，但是在http://fir.im/docs/version_detection fir.im的更新接口中，他没有提供versionCode

**Comment by hugeterry** [comment]
可以在调试的过程中不提高版本数等到发布新版本时再提高😋

**Comment by waincent** [comment]
好的 thank you.

**Comment by xxxifan** [comment]
现已支持编译号`build`
